import type { AppData, Prospect } from "./types";

export const makeId = () => `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;

export const demoProspects: Prospect[] = [
  {
    id: "maya-chen",
    prospectName: "Dr. Maya Chen",
    institution: "UC Berkeley",
    role: "Principal Investigator",
    persona: "Principal Investigator",
    researchField: "Computational Biology",
    source: "Lab website",
    recentContext: "Lab published a new multi-omics methods paper.",
    painPoint: "Literature overload",
    fitScore: 91,
    priority: "High",
    status: "Qualified",
    notes: "Strong fit; lead with staying current across adjacent methods.",
    lastTouch: "Not contacted",
    nextAction: "Send research interview invite",
    channel: "Email",
  },
  {
    id: "alex-rivera",
    prospectName: "Alex Rivera",
    institution: "Stanford",
    role: "PhD Researcher",
    persona: "Researcher",
    researchField: "Materials Science",
    source: "Conference attendee list",
    recentContext: "Works across battery materials and simulation.",
    painPoint: "Finding related papers",
    fitScore: 84,
    priority: "High",
    status: "Contacted",
    notes: "Interested in literature discovery workflow.",
    lastTouch: "2 days ago",
    nextAction: "Follow up with workflow example",
    channel: "LinkedIn",
  },
  {
    id: "jordan-kim",
    prospectName: "Jordan Kim",
    institution: "UCSF",
    role: "Lab Administrator",
    persona: "Lab Administrator",
    researchField: "Neuroscience",
    source: "Referral",
    recentContext: "Coordinates knowledge sharing across a 24-person lab.",
    painPoint: "Lab knowledge organization",
    fitScore: 76,
    priority: "Medium",
    status: "Engaged",
    notes: "Asked how shared research collections work.",
    lastTouch: "Yesterday",
    nextAction: "Share team workflow overview",
    channel: "Email",
  },
  {
    id: "priya-shah",
    prospectName: "Priya Shah",
    institution: "MIT",
    role: "Department Lead",
    persona: "Department Lead",
    researchField: "AI + Science",
    source: "Newsletter",
    recentContext: "Exploring responsible AI tools for research teams.",
    painPoint: "Research productivity",
    fitScore: 88,
    priority: "High",
    status: "Interested",
    notes: "Potential design partner at department level.",
    lastTouch: "4 days ago",
    nextAction: "Book stakeholder demo",
    channel: "Email",
  },
  {
    id: "morgan-lee",
    prospectName: "Morgan Lee",
    institution: "Industry R&D",
    role: "Research Scientist",
    persona: "Industry R&D",
    researchField: "Chemistry",
    source: "Webinar",
    recentContext: "Evaluating research intelligence tooling.",
    painPoint: "Faster technical insight",
    fitScore: 81,
    priority: "High",
    status: "Meeting/Demo",
    notes: "Needs credible security and accuracy answers.",
    lastTouch: "Today",
    nextAction: "Send demo recap",
    channel: "Webinar",
  },
];

export const demoData: AppData = {
  icp: {
    productName: "Valency Bond",
    productDescription:
      "AI research tool that helps researchers work across scientific literature and research workflows.",
    targetICP:
      "Researchers, principal investigators, lab administrators, department leads, and research-heavy institutions.",
    primaryPersonas: "Researcher, PI, Lab Administrator, Department Lead, Industry R&D",
    corePainPoints:
      "Literature overload, staying current, finding relevant papers, synthesizing research, coordinating lab knowledge.",
    primaryConversionGoal: "Early access request or product demo.",
    keyProofPoints:
      "Research-focused AI workflow, built for academic and scientific users, helps organize complex research information.",
    thingsNotToClaim:
      "Do not claim guaranteed discoveries, do not fabricate citations, do not overpromise scientific accuracy.",
  },
  prospects: demoProspects,
  seoExperiments: [
    {
      id: "seo-1",
      experimentName: "Literature review workflow guide",
      targetQuery: "AI literature review tool",
      searchIntent: "Compare tools",
      contentType: "Research workflow guide",
      hypothesis: "A credible workflow guide will convert research evaluators.",
      publishStatus: "Live",
      impressions: 4820,
      clicks: 274,
      signups: 31,
      earlyAccessRequests: 12,
      notes: "Strongest conversion query.",
    },
    {
      id: "seo-2",
      experimentName: "Research paper discovery landing page",
      targetQuery: "research paper discovery AI",
      searchIntent: "Find a solution",
      contentType: "Landing page",
      hypothesis: "Intent-specific copy will improve early access requests.",
      publishStatus: "Live",
      impressions: 7210,
      clicks: 188,
      signups: 18,
      earlyAccessRequests: 5,
      notes: "High impressions; title needs work.",
    },
    {
      id: "seo-3",
      experimentName: "AI for lab knowledge",
      targetQuery: "AI research assistant for labs",
      searchIntent: "Explore workflow",
      contentType: "Blog post",
      hypothesis: "Lab-specific use cases will reach administrators.",
      publishStatus: "Draft",
      impressions: 0,
      clicks: 0,
      signups: 0,
      earlyAccessRequests: 0,
      notes: "Interview two lab administrators before publishing.",
    },
  ],
  outreach: [],
  contentIdeas: [],
};

export const pipelineData = [
  { stage: "Targeted", value: 250 },
  { stage: "Researched", value: 180 },
  { stage: "Qualified", value: 118 },
  { stage: "Contacted", value: 86 },
  { stage: "Engaged", value: 32 },
  { stage: "Interested", value: 19 },
  { stage: "Meeting/Demo", value: 8 },
  { stage: "Active Opportunity", value: 12 },
];
